version: '3'
services:
   db_mb:
    image: postgres:12
    container_name: db_mb
    ports:
      - 5451:5432
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: "America/Fortaleza"